### PR TITLE
Add VS Code suggested extensions

### PR DESCRIPTION
**Pull request by floogulinc**
We should test the new Angular ones, especially Nx Console, in the lab once some of the other changes are in.

### CODE REVIEW

**Comment by floogulinc** [comment]
I don't know about including [Nx Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console). It is pretty nice and gives a GUI for a lot of Angular CLI stuff but it might be more unneeded complexity. 

@NicMcPhee @kklamberty thoughts?

**Comment by kklamberty** [comment]
I'm not sure about the spell checker. Does it think that camel case words are not spelled right? @NicMcPhee and I noticed it caring about things that were not helpful. I think it was that extension - it was one about spelling, and it was not ignoring things we really thought it should iirc.

**Comment by floogulinc** [comment]
The spell checker seems to be pretty smart about stuff like camel case. Here is an example I just noticed:
image

It has dictionaries and specific support for various languages like Java and Typescript (there are more you can turn on in its settings, like Mongo and Gradle).

**Comment by floogulinc** [comment]
Also, for certain specific words we are using a lot that are not real words like `todos` we can add them to a dictionary for the project so they are not shown as misspelled automatically. When you go to fix a word you can select "add to folder dictionary" and it adds it to this section in `.vscode/settings.json`:

```json
{
    "cSpell.words": [
        "todos"
    ]
}
```

**Comment by kklamberty** [comment]
As @floogulinc and I discussed earlier today in person, @NicMcPhee and I had discussed maybe using a TS Linter. If the spelling is smart on most things and can be trained, I think it would be a great idea.

**Pull request merged**
